# Generated by Django 4.2.3 on 2023-09-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='enable',
        ),
    ]
