# Generated by Django 4.2.3 on 2023-09-16 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResourcePreference',
        ),
    ]
