# Generated by Django 4.2.3 on 2025-03-06 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llm_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMSetupEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('response_time', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('llm_setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm_settings.llmsetup')),
            ],
        ),
    ]
