# Generated by Django 4.2.3 on 2025-03-07 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('llm_settings', '0002_llmsetupevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('rating', models.FloatField()),
                ('response_time', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.RemoveField(
            model_name='llmsetupevaluation',
            name='llm_setup',
        ),
        migrations.DeleteModel(
            name='LLMSetup',
        ),
        migrations.DeleteModel(
            name='LLMSetupEvaluation',
        ),
    ]
