# Generated by Django 4.2.3 on 2025-03-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_settings', '0003_setupevaluation_remove_llmsetupevaluation_llm_setup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmmodel',
            name='name',
            field=models.CharField(choices=[('gpt-3.5-turbo', 'gpt-3.5-turbo'), ('text-davinci-003', 'text-davinci-003'), ('text-davinci-002', 'text-davinci-002'), ('text-curie-001', 'text-curie-001'), ('text-babbage-001', 'text-babbage-001'), ('text-ada-001', 'text-ada-001'), ('gpt-4', 'gpt-4'), ('gpt-4-turbo', 'gpt-4-turbo')], max_length=100),
        ),
    ]
