# Generated by Django 4.2.3 on 2025-03-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_settings', '0004_alter_llmmodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='text',
            new_name='template',
        ),
    ]
