# Generated by Django 4.2.3 on 2025-03-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_settings', '0005_rename_text_prompt_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='template_variables',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
