from django.contrib import admin

from .models import Topic, TopicTag, TopicTranslation


class TopicAdmin(admin.ModelAdmin):
    exclude = ('autogenerated',)


class TopicTagAdmin(admin.ModelAdmin):
    exclude = ('number_topics',)


admin.site.register(Topic, TopicAdmin)
admin.site.register(TopicTag, TopicTagAdmin)
admin.site.register(TopicTranslation)

