from django.contrib import admin

from .models import Topic, TopicTag


class TopicAdmin(admin.ModelAdmin):
    exclude = ('autogenerated',)


admin.site.register(Topic, TopicAdmin)
admin.site.register(TopicTag)

