from django.db import models


class Topic(models.Model):
    title = models.CharField(max_length=100)
    enabled = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    premium = models.BooleanField(default=False)
    description = models.CharField(max_length=200, null=True, blank=True)
    autogenerated = models.BooleanField(default=False)

    def get_list_questions(self):
        questions = (card.question for card in self.cards.all())
        return questions

    @classmethod
    def create(cls, title, description, enabled = True, autogenerated = False):
        topic = Topic.objects.create(
            title=title,
            description=description,
            enabled=enabled,
            autogenerated=autogenerated
        )
        return topic

    def __str__(self):
        return f'{self.title} {self.id}'


class TopicTag(models.Model):
    tag = models.CharField(max_length=50)
    topics = models.ManyToManyField(Topic)

    def __str__(self):
        return self.tag