from rest_framework import serializers

from .models import Topic


class TopicListSerializer(serializers.ModelSerializer):

    class Meta:
        model = Topic
        fields = ['id', 'title', 'is_enabled', 'is_premium', 'description', 'is_autogenerated']


class TopicDetailSerializer(serializers.ModelSerializer):

    class Meta:
        model = Topic
        fields = '__all__'
