# Generated by Django 4.2.3 on 2025-03-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topicgeneratorsetup',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='topicgeneratorsetup',
            name='prompt',
        ),
    ]
