# Generated by Django 4.2.3 on 2025-03-07 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llm_settings', '0004_alter_llmmodel_name'),
        ('topic_generator', '0002_alter_topicgeneratorsetup_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicgeneratorsetup',
            name='prompt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='llm_settings.prompt'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='topicgeneratorsetup',
            unique_together={('model', 'prompt')},
        ),
    ]
