# Generated by Django 4.2.3 on 2025-03-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_generator', '0003_topicgeneratorsetup_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicgeneratorsetup',
            name='template_variables',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
