# Generated by Django 4.2.3 on 2025-03-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic_generator', '0004_alter_topicgeneratorsetup_template_variables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicgeneratorsetup',
            name='template_variables',
        ),
    ]
