# Generated by Django 4.2.3 on 2025-03-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_generator', '0005_remove_topicgeneratorsetup_template_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicgeneratorsetup',
            name='examples_to_add',
            field=models.IntegerField(default=0),
        ),
    ]
