# Generated by Django 4.2.3 on 2025-03-09 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("llm_settings", "0006_prompt_template_variables"),
        ("languages", "0003_alter_language_code_alter_language_name"),
        ("topic_generator", "0006_topicgeneratorsetup_examples_to_add"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicTranslatorSetup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "languages_to_translate",
                    models.ManyToManyField(to="languages.language"),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="llm_settings.llmmodel",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="llm_settings.prompt",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("model", "prompt")},
            },
        ),
    ]
