# Generated by Django 4.2.3 on 2025-03-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic_generator", "0007_topictranslatorsetup"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicgeneratorsetup",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="topictranslatorsetup",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
