# Generated by Django 4.2.3 on 2025-03-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic_generator", "0008_topicgeneratorsetup_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
            ],
        ),
    ]
