# Generated by Django 4.2.3 on 2025-03-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topic_generator", "0010_alter_generationsettings_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="topicgeneratorsetup",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="topictranslatorsetup",
            unique_together=set(),
        ),
    ]
