# Generated by Django 4.2.3 on 2025-03-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topic_generator", "0011_alter_topicgeneratorsetup_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="generationsettings",
            old_name="enabled",
            new_name="is_enabled",
        ),
        migrations.RenameField(
            model_name="topicgeneratorsetup",
            old_name="enabled",
            new_name="is_enabled",
        ),
        migrations.RenameField(
            model_name="topictranslatorsetup",
            old_name="enabled",
            new_name="is_enabled",
        ),
    ]
