# Generated by Django 4.2.3 on 2023-09-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
