# Generated by Django 4.2.3 on 2023-09-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_favorite_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
