# Generated by Django 4.2.3 on 2023-09-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_topictag'),
    ]

    operations = [
        migrations.AddField(
            model_name='topictag',
            name='topics',
            field=models.ManyToManyField(to='topics.topic'),
        ),
    ]
