# Generated by Django 4.2.3 on 2023-09-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_topictag_topics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='enable',
            new_name='enabled',
        ),
    ]
