# Generated by Django 4.2.3 on 2023-09-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_topic_autogenerated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='number_questions',
        ),
    ]
