# Generated by Django 4.2.3 on 2024-03-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0011_topic_lang_topic_reference_topic_translate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topictranslation',
            name='translated_de',
        ),
        migrations.RemoveField(
            model_name='topictranslation',
            name='translated_es',
        ),
        migrations.AddField(
            model_name='topictranslation',
            name='translate_de',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topictranslation',
            name='translate_es',
            field=models.BooleanField(default=True),
        ),
    ]
