# Generated by Django 4.2.3 on 2024-03-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_alter_language_code_alter_language_name'),
        ('topics', '0013_remove_topictranslation_translate_de_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='translate',
        ),
        migrations.AlterField(
            model_name='topictranslation',
            name='languages',
            field=models.ManyToManyField(to='languages.language'),
        ),
    ]
