# Generated by Django 4.2.3 on 2025-03-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0015_topiccard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topiccard',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='topiccard',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
