# Generated by Django 4.2.3 on 2025-03-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0017_topic_cards'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicCard',
        ),
    ]
