# Generated by Django 4.2.3 on 2025-03-07 13:29

from django.db import migrations, models
import django.db.models.deletion
import languages.utils


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_alter_language_code_alter_language_name'),
        ('topics', '0018_delete_topiccard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='lang',
            field=models.ForeignKey(default=languages.utils.get_default_language, on_delete=django.db.models.deletion.CASCADE, to='languages.language'),
        ),
    ]
