# Generated by Django 4.2.3 on 2025-03-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0019_alter_topic_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='cards',
            new_name='questions',
        ),
    ]
