# Generated by Django 4.2.3 on 2025-03-09 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0021_rename_created_topic_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="reference",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference used to translate to other languages",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="topics.topic",
            ),
        ),
    ]
