import React from 'react';
import '../../assets/css/Tag.css';
import { Badge } from 'react-bootstrap';

function Autogenerated() {
  return (
    <Badge
      bg="secondary"
      className="Autogenerated Tag"
    >
      <i className="bi bi-robot" />
      Autogenerated
    </Badge>
  );
}

export default Autogenerated;
