import React from 'react';
import '../../assets/css/Tag.css';
import PremiumTag from './PremiumTag';
import AutogeneratedTag from './AutogeneratedTag';

function TagList({ topic }) {
  return (
    <div className="TagList">
      {topic.premium && <PremiumTag />}
      {topic.autogenerated && <AutogeneratedTag />}
    </div>
  );
}

export default TagList;
