# Generated by Django 4.2.3 on 2024-03-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(default='french', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
